---
title: "RNA-Seq Exploratory Analysis"
output:
  pdf_document: default
  html_document: default
date: "2024-08-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
# Set so that long lines in R will be wrapped:
opts_chunk$set(tidy.opts=list(width.cutoff=40),tidy=TRUE)
```


```{r}
suppressPackageStartupMessages({
  library(here)
  library(tidyverse)
  library(biomaRt)
  library(factoextra)
  library(ggrepel)
  library(caret)
  
  library(DESeq2)
  library(enrichR)
  library(xlsx)
  library(circlize)
  library(ComplexHeatmap)
})

main_folder <- here()
```

```{r}
count_paths <- list.files(path = file.path(main_folder,"count_data"), pattern = "quant.genes.sf", recursive = T, full.names = T)
count_lists <- lapply(count_paths, function (x) read_tsv(x, col_types = cols()))
names <- lapply(basename(count_paths), function (x) strsplit(x, split = "-")[[1]][1])
names(count_lists) <- names
counts <- count_lists %>%
  lapply(., function(df) {df %>% dplyr::select(Name,NumReads)}) %>%
  # Map(function(x, n) setNames(x, c(names(x)[1], n)), ., names(.))
  Map(function(x, n) setNames(x, c("Ensembl_ID", n)), ., names(.)) %>%
  purrr::reduce(inner_join, by = c("Ensembl_ID")) %>%
  as.data.frame(.) %>% 
  mutate_if(is.numeric, round)
# write.table(counts, file.path(main_folder,"gene_counts.tsv"), quote = F, sep = "\t", row.names = F, col.names = T)
```

```{r}
tpm <- count_lists %>%
  lapply(., function(df) {df %>% dplyr::select(Name,TPM)}) %>%
  Map(function(x, n) setNames(x, c("Ensembl_ID", n)), ., names(.)) %>%
  purrr::reduce(inner_join, by = c("Ensembl_ID")) %>%
  as.data.frame(.)
```


Convert Ensembl IDs to gene names
```{r}
ensembl <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
genes <- data.frame(ensembl = tpm$Ensembl_ID)
# run the query
gene_IDs <- getBM(
  attributes=c("ensembl_gene_id_version","hgnc_symbol","gene_biotype"),
  filters=c("ensembl_gene_id_version"), 
  values = genes$ensembl,
  mart = ensembl)
head(gene_IDs)
```

tpm matrix is updated by matching to the retrieved annotation
```{r}
gene_IDs <- gene_IDs %>%
  filter(!hgnc_symbol=="") 

tpm <- tpm %>%
  dplyr::rename("ensembl_gene_id_version" = "Ensembl_ID") %>%
  right_join(.,gene_IDs) %>%
  dplyr::select(-gene_biotype, -ensembl_gene_id_version) %>%
  group_by(hgnc_symbol) %>%
  summarise_all(mean) %>%
  column_to_rownames("hgnc_symbol") %>%
  rownames_to_column("gene_id")
head(tpm)

# write.table(tpm, file.path(main_folder,"acc_cibersort_input.tsv"), quote = F, sep = "\t", row.names = F, col.names = T)
```


```{r}
vst <- read.table(file.path(main_folder,"differential_analysis_0824/deseq_vst_data.txt"))
colnames(vst) <- gsub("^X","",colnames(vst))

pca_data=prcomp(t(vst))
summary(pca_data)

p1 <- fviz_eig(pca_data, 
         addlabels = TRUE, 
         ylim = c(0, 70),
         main="")
p1

png(file.path(main_folder,"pca_screeplot.png"), res=300, units = "px", width=2500, height=2000)
p1
dev.off()
```

```{r}
pca_data_perc=round(100*pca_data$sdev^2/sum(pca_data$sdev^2),1)
df_pca_data = data.frame(PC1 = pca_data$x[,1], PC2 = pca_data$x[,2], sample = colnames(vst))

# PCA for components 1&2
p2 <- ggplot(df_pca_data, aes(PC1,PC2, colour = "#d95d39"))+
  geom_point(size=3)+
  scale_color_manual(values=c("#d95d39"))+
  labs(x=paste0("PC1 (",pca_data_perc[1],"% variance)"), y=paste0("PC2 (",pca_data_perc[2],"% variance)") )+
  theme(legend.position="none")
p2


# PCA with labels
p3 <- ggplot(df_pca_data, aes(PC1,PC2, colour = "#d95d39"))+
  geom_point(size=3, show.legend = F)+
  scale_color_manual(values=c("#d95d39"))+
  geom_label_repel(aes(label=sample, fill="#d95d39"), color="white", size=2, max.overlaps = Inf)+
  scale_fill_manual(values=c("#d95d39"))+
  labs(x=paste0("PC1 (",pca_data_perc[1],"% variance)"), y=paste0("PC2 (",pca_data_perc[2],"% variance)") )+
  theme(legend.position="none")
p3

png(file.path(main_folder,"PC1_vs_PC2.png"), res=300, units = "px", width=2500, height=2000)
p2
dev.off()
png(file.path(main_folder,"PC1_vs_PC2_labels.png"), res=300, units = "px", width=2500, height=2000)
p3
dev.off()

```

```{r}
# PCA for components 1&3
df_pca_data = data.frame(PC1 = pca_data$x[,1], PC3 = pca_data$x[,3], sample = colnames(vst))

p4 <- ggplot(df_pca_data, aes(PC1,PC3, colour = "#d95d39"))+
  geom_point(size=3)+
  scale_color_manual(values=c("#d95d39"))+
  labs(x=paste0("PC1 (",pca_data_perc[1],"% variance)"), y=paste0("PC3 (",pca_data_perc[3],"% variance)") )+
  theme(legend.position="none")
p4

png(file.path(main_folder,"PC1_vs_PC3.png"), res=300, units = "px", width=2500, height=2000)
p4
dev.off()
```



```{r}
metadata <- readxl::read_xlsx(file.path(main_folder,"Recap_PEVO_data_RNAseq.xlsx"))
samples <- data.frame("sample" = colnames(counts)[2:51])

metadata_selection <- as.data.frame(inner_join(metadata, samples, by = join_by(`Tumor/RNA ID` == sample)))
dim(metadata_selection)
# missing samples
samples %>%
  filter(!sample %in% metadata_selection$`Tumor/RNA ID`)
# Tumor/RNA ID entry in metadata file for those samples is 10067276/5
metadata_selection[nrow(metadata_selection) + 1,] = c("P-0022","10067275","10067150","Cervix","Cervix","Baseline")
metadata_selection[nrow(metadata_selection) + 1,] = c("P-0022","10067276","10067150","Cervix","Cervix","Baseline")
dim(metadata_selection)

groups01 <- metadata_selection %>%
  dplyr::select(`Tumor/RNA ID`,`Timepoint of the tumor`) %>%
  dplyr::rename("sample"="Tumor/RNA ID", "group"="Timepoint of the tumor")
groups01 <- groups01[match(colnames(counts)[2:51], groups01$sample),]
groups01 %>%
  dplyr::count(group)


# baseline VS treatment with HDAC inhibitors
# C3D1, Day 1 of chemotherapy treatment cycle 3
comparisons01 <- data.frame(treatment = c("C3D1","Progression"), 
                          control = c("Baseline","C3D1"))
```

```{r}
counts_hgnc <- counts %>%
  dplyr::rename("ensembl_gene_id_version" = "Ensembl_ID") %>%
  right_join(.,gene_IDs) %>%
  dplyr::select(-gene_biotype, -ensembl_gene_id_version) %>%
  group_by(hgnc_symbol) %>%
  summarise_all(mean) %>%
  column_to_rownames("hgnc_symbol") %>%
  rownames_to_column("gene_id")
```


AUTOGO
```{r}
files <- list.files(path = file.path(main_folder,"auto-go/R"), recursive = T, all.files = T, full.names = T)
invisible(sapply(files, source))

autogo_folder <- file.path(main_folder,"")
```

```{r warning=FALSE, echo=TRUE, results='hide'}
deseq_analysis(counts_hgnc, groups01, comparisons01, padj_threshold = 0.05, log2FC_threshold = 1, pre_filtering = T, save_excel = T, where_results = autogo_folder, outfolder = "differential_analysis_0824/")
```

TPM filtering on baseline expression
```{r}
baseline <- groups01 %>%
  filter(group=="Baseline") %>%
  pull(sample)
c3d1 <- groups01 %>%
  filter(group=="C3D1") %>%
  pull(sample)
  
expression_filter_baseline <- tpm %>%
  dplyr::select(any_of(c("gene_id",baseline))) %>%
  column_to_rownames("gene_id")
expression_filter_baseline$mean_baseline <- apply(expression_filter_baseline, 1, mean) 
expression_filter_baseline <- expression_filter_baseline %>%
  rownames_to_column("gene_id")

expression_filter_c3d1 <- tpm %>%
  dplyr::select(any_of(c("gene_id",c3d1))) %>%
  column_to_rownames("gene_id")
expression_filter_c3d1$mean_c3d1 <- apply(expression_filter_c3d1, 1, mean) 
expression_filter_c3d1 <- expression_filter_c3d1 %>%
  rownames_to_column("gene_id")

expression_filter <- inner_join(expression_filter_baseline,expression_filter_c3d1, by="gene_id") %>%
  dplyr::select(gene_id,mean_baseline,mean_c3d1)
filter_out <- expression_filter %>%
  filter(mean_baseline<=1 | mean_c3d1<=1)
```

```{r include = FALSE}
DE_Baseline_vs_C3D1_allres <- readxl::read_xlsx(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/DE_Baseline_vs_C3D1_allres.xlsx")) %>%
  filter(!genes %in% filter_out$gene_id) %>%
  as.data.frame(.)
write.xlsx(DE_Baseline_vs_C3D1_allres, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/DE_Baseline_vs_C3D1_allres.xlsx"), row.names = F, append = F)

DE_Baseline_vs_C3D1_allres.tsv <- read_tsv(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/DE_Baseline_vs_C3D1_allres.tsv"), show_col_types = FALSE) %>%
  filter(!genes %in% filter_out$gene_id)
write.table(DE_Baseline_vs_C3D1_allres.tsv, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/DE_Baseline_vs_C3D1_allres.tsv"), quote = F, sep = "\t", row.names = F, col.names = T)


filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05 <- readxl::read_xlsx(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05.xlsx"))

filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1 <- filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05 %>%
  left_join(.,expression_filter, by = join_by(`genes` == gene_id)) %>%
  filter(mean_baseline>1 | mean_c3d1>1) %>%
  dplyr::select(-mean_baseline,-mean_c3d1) %>%
  as.data.frame(.)
write.xlsx(filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1.xlsx"), row.names = F)

down <- read_table(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/down_genes_Baseline_vs_C3D1/down_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), col_names = "gene") %>%
  filter(gene %in% filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1$genes)
write.table(down, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/down_genes_Baseline_vs_C3D1/down_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), quote = F, sep = "\t", row.names = F, col.names = F)
  
up <- read_table(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/up_genes_Baseline_vs_C3D1/up_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), col_names = "gene") %>%
  filter(gene %in% filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1$genes)
write.table(up, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/up_genes_Baseline_vs_C3D1/up_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), quote = F, sep = "\t", row.names = F, col.names = F)

up_down <- read_table(file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/up_down_genes_Baseline_vs_C3D1/up_down_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), col_names = "gene") %>%
  filter(gene %in% filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05_TPM1$genes)
write.table(up_down, file.path(main_folder,"differential_analysis_0824/Baseline_vs_C3D1/filtered_DE_Baseline_vs_C3D1_thFC1_thPval0.05/up_down_genes_Baseline_vs_C3D1/up_down_genes_list_Baseline_vs_C3D1_thFC1_thPval0.05.txt"), quote = F, sep = "\t", row.names = F, col.names = F)
```

```{r warning=FALSE, message=FALSE, echo=TRUE, results='hide'}
path_res <- file.path(main_folder,"differential_analysis_0824/")
all_path_res <- list.files(path = path_res, pattern = "_allres.tsv", recursive = T, full.names = T)
res_lists <- lapply(all_path_res, function (x) read_tsv(x, col_types = cols()))
names(res_lists) <- gsub(paste0(path_res,"/|/DE_.*"), "",all_path_res)

# for (th in c(1)) {
#   lapply(names(res_lists), function (i) volcanoplot(res_lists[[i]], my_comparison = i, log2FC_thresh = th, padj_thresh = 0.05, where_results = autogo_folder, outfolder = "differential_analysis_0824/"))
# }

for (th in c(1)) {
  lapply(names(res_lists), function (i) volcanoplot_tpm(res_lists[[i]], my_comparison = i, log2FC_thresh = th, padj_thresh = 0.05, where_results = autogo_folder, outfolder = "differential_analysis_0824/"))
}
```


```{r warning=FALSE, message=FALSE, echo=TRUE, results='hide'}
# Reading gene lists for enrichment 
lista_p005_fc1 <- read_gene_list(where_results = autogo_folder, outfolder = "differential_analysis_0824/", log2FC_threshold=1, padj_threshold = 0.05, which_list = "everything")

# Enrichment analysis
lapply(names(lista_p005_fc1), function (i) autoGO(lista_p005_fc1[[i]], my_comparison = i, dbs = c("GO_Molecular_Function_2021", "GO_Cellular_Component_2021", "GO_Biological_Process_2021", "KEGG_2021_Human"), where_results = autogo_folder, outfolder = "differential_analysis_0824/", excel = T))


tab_p005_fc1 <- read_enrich_tables(where_results = autogo_folder, outfolder = "differential_analysis_0824/", log2FC_threshold = 1, padj_threshold = 0.05, which_list = "everything")
invisible(lapply(names(tab_p005_fc1), function (i) barplotGO(tab_p005_fc1[[i]], my_comparison = i, where_results = autogo_folder, outfolder = "differential_analysis_0824/")))
invisible(lapply(names(tab_p005_fc1), function (i) lolliGO(tab_p005_fc1[[i]], my_comparison = i, where_results = autogo_folder, outfolder = "differential_analysis_0824/")))
```


```{r}
groups02 <- metadata_selection %>%
  dplyr::select(`Tumor/RNA ID`,`Primary Cancer Type`) %>%
  dplyr::rename("sample"="Tumor/RNA ID", "group"="Primary Cancer Type")
groups02 <- groups02[match(colnames(counts)[2:51], groups02$sample),]
groups02 %>%
  dplyr::count(group)
```





```{r}
## Hierarchical Clustering

# feature selection
# keep top genes based on median absolute deviation
mads <- apply(vst,1,mad)
# selecting features
mad2k <- vst[rev(order(mads))[1:2000],]

# calculate distances (default: Eucledian distance)
dist_matrix <- dist(t(mad2k))
# perform hierarchical clustering using ? linkage 
hc <- hclust(dist_matrix, method = "ward.D2")
plot(hc, main = "", hang = -1, cex = 0.6, xlab="")
fviz_nbclust(mad2k, FUN = hcut, method = "wss")

prediction <- cutree(hc, k = 4)
prediction
```

```{r warning=FALSE}
levels <- groups02 %>%
  mutate(level = ifelse(group=="Anus",1,"")) %>%
  mutate(level = ifelse(group=="Cervix",2,level)) %>%
  mutate(level = ifelse(group=="Head and Neck",3,level)) %>%
  mutate(level = ifelse(group=="Lung",4,level)) %>%
  mutate(level = ifelse(group=="Penis",5,level)) %>%
  mutate(level = ifelse(group=="Vulva",6,level))
target <- levels$level

Reference = groups02$group
Prediction <- cutree(hc, k = 4)
table(Prediction,Reference)
confusionMatrix(as.factor(Prediction), as.factor(target), mode = "everything")
```

